### ISSUE TITLE
Article feedback

### ISSUE THREAD

**Issue by SgtPooki** [tabcat/dynamic-content#1]
https://github.com/tabcat/dynamic-content/blob/master/ARTICLE.md

### Overall feedback

* Needs a Table of contents
* Great article, very well written! I'm excited.
* I love the [Sample Outputs](https://github.com/tabcat/dynamic-content/blob/master/ARTICLE.md#sample-outputs) section

#### Understanding Key Components

This is a great primer.

#### Achieving Dynamicity

* It could be good to show a diagram of what the architecture of OrbitDB -- or other methods people have used to achieve dynamicity -- used to look like, so we could compare.

#### Dynamic-Content IDs

referring to this section: https://github.com/tabcat/dynamic-content/blob/e4df337d4f806ba530efa94b01e7bda2432ffa8d/ARTICLE.md?plain=1#L48-L56

> Instead, it is a permutation of the CID of an immutable manifest document that describes the dynamic content

This is slightly confusing

I know there is a note that says, "there is an example using this in the bottom," but I think this section could explain more, and set expectations better. 

Some questions I have when targeting just this section

- Why do we need this dynamic CID, what is it's purpose?
- Why do i need this manifest json/hashtable/other data?
    - what if someone used `manifest = "myManifest"` (maybe deserves FAQ entry?)
    - What if there are accidental manifest conflicts for different implementations? (FAQ?)

I think briefly speaking about how this DCID is used as a reference point for the implemented application is important. "This is the key used to query the DHT to determine where offline data we need is" and "This is the key used to publish data, so when we go offline, others can find it" or similar. 

* It could be good to link to the https://github.com/tabcat/dynamic-content/blob/master/ARTICLE.md#read-and-write-steps section to point users to how it's used.

#### Viewed as a Replication Protocol

* I feel like it could be useful to link to, or briefly discuss, orbitDB's attempts and problems earlier in this article to explain the reason for this approach.

##### Replication

> When other collaborators are online, use an application-specific replication protocol for real-time collaboration.

It could be valuable to address this further. 
* Why bifurcate replication protocol methods? 
* Is the "app specific" replication protocol using IPFS?
* If not, why not full IPFS?

#### Roadblock, Workaround, and Hopeful Future

* Maybe this section needs more attention and breaking up? Maybe a "blockers" section and current workarounds?

#### Read and Write Steps - https://github.com/tabcat/dynamic-content/blob/master/ARTICLE.md#read-and-write-steps

* I think this basic "algorithm" for your approach should be much higher in the document.

**Comment by tabcat** [comment]
@SgtPooki Thank you for the in-depth review :pray: 

It looks like the critiques boil down to:

- [ ] Reorg Achieving Dynamicity and Viewed as a Replication Protocol sections
- [ ] Explain dynamic-content ids better and why they exist
- [ ] Improve Roadblock section and add Blockers
- [ ] Find earlier place in Article for Read and Write Steps

Missing anything? Going to add to the issue descriptions for what they will include.

**Comment by tabcat** [comment]
Thanks again for feedback. I really like the changes in #2 

Let me know if there is something I missed.

**Comment by SgtPooki** [comment]
Will look tomorrow, i like how you broke the different items into individual issues. Nice work

**Comment by tabcat** [comment]
Going to rewrite a bunch of it tonight. If you want to look tomorrow or the day after that would be great :100:

**Comment by tabcat** [comment]
Ah just saw your slack message :+1:

**Comment by tabcat** [comment]
If something else comes to mind feel free to open another issue.
